### ISSUE TITLE
Make complete packages mockable

### ISSUE THREAD

**Issue by as-design** [joke/spock-mockable#136]
Hi there, we have a lot data classes in our project that we have to mock. Instead of making each class mockable it would be handy to make complete packages mockable. Here is a proposal #135

**Comment by as-design** [comment]
#135

**Comment by joke** [comment]
Hi,

I'll have to look into it. I once thought of something familiar but ran into problems with the modification process caused by the class loading order.

**Comment by as-design** [comment]
Thanks @joke . Good point with the test classes. I have added a filter for test classes in my PR.

**Comment by joke** [comment]
Thanks. I'll take a closer look during the weekend.

**Comment by as-design** [comment]
Thanks for your support and merging the feature. 

Just one Question: Is it correct that the new version uses a new version scheme? `v.1.5.0` vs. `1.4.4` 
https://mvnrepository.com/artifact/io.github.joke/spock-mockable

**Comment by joke** [comment]
That was unintentional. I will fix it.
Thank you for the feedback.

**Comment by joke** [comment]
@as-design The new version 1.5.1 is available.

**Comment by as-design** [comment]
@joke Perfect 👍
