### ISSUE TITLE
Compatibility with Byte-Buddy 1.12.13+

### ISSUE THREAD

**Issue by gesellix** [joke/spock-mockable#208]
Byte-Buddy v1.12.13 has a breaking api change, which makes spock-mockable fail in combination with the newest byte-buddy release. It seems like the api change will be kept as is, see https://github.com/raphw/byte-buddy/issues/1297.
This is just a heads-up, I didn't dig deeper to look if I could fix it myself by creating a pull request.

**Comment by henrik242** [comment]
I'm seeing the same thing. Looking forward to a fix :)

**Comment by joke** [comment]
Thank you very much. The new release with an updated dependency on byte buddy will be available shortly.
