### ISSUE TITLE
Support for jdk dynamic proxy class

### ISSUE THREAD

**Issue by CoderYellow** [joke/spock-mockable#241]
Sometimes we want to mock some jdk proxy class like mybatis mapper interface implementation, it is generated at runtime, we don't know its type ahead.
Is there any solution to achieve this?

**Comment by joke** [comment]
@CoderYellow

It's kind of tricky. I'm not entirely sure if the class would be detected by the instrumentation agent.
But you try adding a `@Mockable(packages = "...")` annotation with the package of the generated class. This way the class would be modified if the dynamically generated class would be detected at all.

If you could provide an example it would definitely help with analysis.

Regards
Joke
