### ISSUE TITLE
This is global affected?

### ISSUE THREAD

**Issue by LintaoAmons** [joke/spock-mockable#264]
I found that I use annotation to mock one final class in one test class, but this also affects other tests that not suppose to be mocked.

Is it possible to only mock the class when annotated in the test class specifically.

**Comment by joke** [comment]
Hi @LintaoAmons ,

unfortunately it is not possible. Take a look at [How does it work](https://github.com/joke/spock-mockable#how-does-it-work).

The extensions works by using class transformation during startup and so spock can do it's normal mocking.
Class transformation affects the entire JVM and it's not possible re-define classes back and forth. This only works if you are using a JVM with [dcevm](http://dcevm.github.io/) and even if this would be the case it would raise lots of problems with parallel test execution.

**Comment by LintaoAmons** [comment]
Is it possible to add some things like a toggle to the byte codes? Though the modification is globalwise but the toggle can switch on when found that the test class is annotated with mockable, and keep off otherwise.

**Comment by joke** [comment]
Sounds more like you want to call the real implementation. That can be done with normal spock:
```
mock.someMethod() >> { callRealMethod() }
```

But it what can not be done
```
// modify visibility
test1 {
  checkIfMethodXIsProtected
}

// revert visibility
test2 {
  checkIfMethodXIsPrivate
}
