### ISSUE TITLE
Artifacts missing?

### ISSUE THREAD

**Issue by gesellix** [joke/spock-mockable#269]
I'm using spock-mockable in a Gradle project and it seems the releases 2.0.0 and 2.1.0 aren't working anymore. Looking at Maven Central and the GitHub Packages, it seems like the publishing changed to a `*-all` artifact only instead of multiple `*-javadoc`, `*.jar`, etc like for release 1.5.7. The published .pom doesn't seem to match the -all artifact. See [1.5.7](https://repo1.maven.org/maven2/io/github/joke/spock-mockable/1.5.7/) compared to [2.1.0](https://repo1.maven.org/maven2/io/github/joke/spock-mockable/2.1.0/).

Can you verify that the published artifacts are working like expected?

**Comment by joke** [comment]
Thank you.

The new artifacts should be published soon.

**Comment by gesellix** [comment]
Thanks a lot for the quick fix!
