### ISSUE TITLE
Cannot get property 'absolutePath' on null object

### ISSUE THREAD

**Issue by ThomHehl** [joke/spock-mockable#366]
Following your directions, I have the following lines in my build.gradle.

    testImplementation (
            'org.junit.jupiter:junit-jupiter-api:5.8.1',
            'org.spockframework:spock-core:2.4-M1-groovy-4.0',
            'io.github.joke:spock-mockable:2.3.1',
            'cglib:cglib-nodep:3.3.0'
    )

and

// to load the agent even earlier add it as a JVM argument
tasks.withType(Test) {
    jvmArgs += ["-javaagent:${classpath.find { it.name.contains('spock-mockable') }.absolutePath}"]
}

The error I'm getting is on the jvmArgs +- line.

I'm pretty sure it's a chicken and egg problem, but not sure how to resolve it. I thought about parsing out the classpath.find and null checking before including, but not really sure of the syntax.

**Comment by joke** [comment]
@ThomHehl you could try something like that:

```
jvmArgs += ["-javaagent:${classpath.find { it.name.contains('spock-mockable') }?.absolutePath}"
```
That should at least make the statement null safe.

**Comment by joke** [comment]
This issue might be related to #367. The published pom did contain the wrong information.
